name: semver

on:
  workflow_dispatch:
    branches:
      - master
      - sw0nt-dev
  push:
    branches:
      - master
      - sw0nt-dev

jobs:
  prepare:
    name: Prepare pre-release
    runs-on: ubuntu-latest

    outputs:
      pre-release_tag: ${{ steps.latest_tag.tag_name }}

    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Finding the latest tag
        id: latest_tag
        run: |
          current_semver=$(git tag --list | grep '^v[0-9]*\.[0-9]*\.[0-9]*$' | tail -n 1)
          current_major=$(echo $current_semver | sed -E 's/v([0-9]*)\.([0-9]*)\.([0-9]*)/\1/g')
          current_minor=$(echo $current_semver | sed -E 's/v([0-9]*)\.([0-9]*)\.([0-9]*)/\2/g')
          current_patch=$(echo $current_semver | sed -E 's/v([0-9]*)\.([0-9]*)\.([0-9]*)/\3/g')
          next_patch=$((current_patch+1))
          next_semver="v$current_major.$current_minor.$next_patch-pre-release"
          echo "current semver: $current_semver"
          echo "next pre-release semver: $next_semver"
          echo "::set-output name=tag_name::${next_semver}"
        shell: bash

  test-tag-name:
    name: Test tag_name
    needs: prepare
    runs-on: ubuntu-latest

    steps:
      - name: print tag_name
        env:
          VERSION: ${{ needs.prepare.outputs.pre-release_tag }}
        run: |
          echo "2nd job: ${VERSION}"


